import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { db } from "@/db/client";
import { SiteShell } from "@/components/SiteShell";
import {
  loadPublishedArticle,
  stripLinkMarkers,
} from "@/lib/content-machine/publish";

// Split body markdown into two halves at a sensible boundary so we can
// insert an inline image between them. Prefers splitting at the H2
// nearest the middle of the body; falls back to a midpoint paragraph
// break. Returns [first, second] — second may be empty for very short
// bodies (in which case we just skip the inline image).
function splitBodyForInlineImage(body: string): [string, string] {
  const lines = body.split("\n");
  const h2Indices: number[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (/^##\s+/.test(lines[i])) h2Indices.push(i);
  }
  const mid = Math.floor(lines.length / 2);
  if (h2Indices.length >= 2) {
    // Pick the H2 line closest to the midpoint (but skip the first H2
    // — inserting before the first section header would push the image
    // too high in the article).
    let best = h2Indices[1];
    for (const idx of h2Indices.slice(1)) {
      if (Math.abs(idx - mid) < Math.abs(best - mid)) best = idx;
    }
    return [lines.slice(0, best).join("\n"), lines.slice(best).join("\n")];
  }
  // No usable H2 — fall back to a blank-line break near the middle.
  for (let i = mid; i < lines.length; i++) {
    if (lines[i].trim() === "") {
      return [lines.slice(0, i).join("\n"), lines.slice(i + 1).join("\n")];
    }
  }
  return [body, ""];
}

// Published articles from the content machine. One row per published
// article in the `articles` table. Slugs are kebab-case and unique.
// See docs/CDLAjobs_Daily_Article_Prompt.md for the article structure
// the LLM produces and src/lib/content-machine/* for the pipeline.
//
// ISR matches the rest of the dynamic pages on this site (15 min) so a
// fresh publish appears on the live URL within one ISR window.

export const revalidate = 900;

const BUCKET_LABELS: Record<number, string> = {
  1: "Pay & Money",
  2: "Career Strategy",
  3: "Life on the Road",
  4: "How the Job-Search System Works",
};

interface PageParams {
  slug: string;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<PageParams>;
}): Promise<Metadata> {
  const { slug } = await params;
  const article = await loadPublishedArticle(db, slug);
  if (!article) return { title: "Article not found" };

  return {
    title: article.titleTag,
    description: article.metaDescription,
    alternates: { canonical: article.publishedUrl ?? undefined },
    openGraph: {
      title: article.titleTag,
      description: article.metaDescription,
      type: "article",
      url: article.publishedUrl ?? undefined,
      publishedTime: article.publishedAt?.toISOString(),
    },
    twitter: {
      card: "summary",
      title: article.titleTag,
      description: article.metaDescription,
    },
  };
}

export default async function ArticlePage({
  params,
}: {
  params: Promise<PageParams>;
}) {
  const { slug } = await params;
  const article = await loadPublishedArticle(db, slug);
  if (!article) notFound();

  const bodyForRender = stripLinkMarkers(article.bodyMarkdown);
  const bucketLabel = BUCKET_LABELS[article.bucket] ?? `Bucket ${article.bucket}`;
  const altText = article.title;

  // Only split the body when an inline image is actually available.
  const [bodyFirstHalf, bodySecondHalf] = article.inlineImageUrl
    ? splitBodyForInlineImage(bodyForRender)
    : [bodyForRender, ""];

  // FAQPage JSON-LD goes in a <script> tag at the top of the page body.
  // The LLM is instructed to make the schema text match the on-page FAQ
  // exactly (Google's requirement).
  const faqJsonLd = article.faqSchemaJsonld?.trim()
    ? article.faqSchemaJsonld
    : null;

  return (
    <SiteShell>
      {faqJsonLd && (
        <script
          type="application/ld+json"
          // The schema text is generated by the LLM and stored in our
          // DB. It's not user-provided. Still rendered verbatim — Google
          // requires the schema to exactly match the on-page FAQ text.
          dangerouslySetInnerHTML={{ __html: faqJsonLd }}
        />
      )}

      <article className="mx-auto max-w-3xl px-5 py-10">
        <header className="mb-6">
          <p className="text-xs uppercase tracking-wide text-brand-muted">
            {bucketLabel}
            {article.region ? ` · ${article.region}` : null}
          </p>
          <h1 className="mt-2 text-3xl font-semibold text-brand-deep">
            {article.title}
          </h1>
          {article.publishedAt && (
            <p className="mt-3 text-sm text-brand-muted">
              Published{" "}
              <time dateTime={article.publishedAt.toISOString()}>
                {article.publishedAt.toLocaleDateString("en-US", {
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                })}
              </time>
            </p>
          )}
        </header>

        {article.heroImageUrl && (
          <figure className="mb-8 overflow-hidden rounded-md border border-brand-rule">
            <Image
              src={article.heroImageUrl}
              alt={altText}
              width={1536}
              height={1024}
              priority
              className="h-auto w-full"
              sizes="(min-width: 768px) 768px, 100vw"
            />
          </figure>
        )}

        <div
          // Tailwind typography would normally render this; using
          // explicit className styles for consistency with the rest of
          // the site which doesn't use @tailwindcss/typography.
          className="article-body space-y-4 text-base leading-relaxed text-brand-ink"
        >
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {bodyFirstHalf}
          </ReactMarkdown>

          {article.inlineImageUrl && bodySecondHalf && (
            <figure className="my-8 overflow-hidden rounded-md border border-brand-rule">
              <Image
                src={article.inlineImageUrl}
                alt={altText}
                width={1024}
                height={1024}
                className="h-auto w-full"
                sizes="(min-width: 768px) 768px, 100vw"
              />
            </figure>
          )}

          {bodySecondHalf && (
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {bodySecondHalf}
            </ReactMarkdown>
          )}
        </div>

        {article.honestCaveat?.trim() && (
          <section className="mt-10 rounded-md border border-brand-rule bg-brand-surface p-5">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-brand-muted">
              Honest caveat
            </h2>
            <div className="mt-2 text-sm text-brand-ink">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {article.honestCaveat}
              </ReactMarkdown>
            </div>
          </section>
        )}

        {article.ctaBlock?.trim() && (
          <section className="mt-10 rounded-md border border-brand-deep bg-brand-deep p-6 text-brand-paper">
            <div className="text-base leading-relaxed">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {article.ctaBlock}
              </ReactMarkdown>
            </div>
            <Link
              href="/intake"
              className="mt-4 inline-block rounded-md bg-brand-gold px-5 py-2 text-sm font-semibold text-brand-deep hover:opacity-90"
            >
              Start your intake — it takes 6 minutes
            </Link>
          </section>
        )}
      </article>
    </SiteShell>
  );
}
